trigger:
- master

stages:
  - stage: CI
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Build
        steps:
        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'clean package'

        - task: DockerInstaller@0
          displayName: 'Install'
          inputs:
            dockerVersion: '17.09.0-ce'

        - task: Docker@2
          displayName: 'Build and Push'
          inputs:
            containerRegistry: 'Docker Registry'
            repository: 'kvncont/hello-world'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.BuildId)'

  - stage: CD
    dependsOn: CI
    jobs:
    - deployment: Development
      displayName: 'Deploy Development'
      workspace:
        clean: all
      # condition: string
      continueOnError: false
      # container: containerReference # container to run this job inside
      # services: { string: string | container } # container resources to run as a service container
      # timeoutInMinutes: nonEmptyString        # how long to run the job before automatically cancelling
      # cancelTimeoutInMinutes: nonEmptyString  # how much time to give 'run always even if cancelled tasks' before killing them
      # variables: # several syntaxes, see specific section
      environment: Develoment.default
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            # - checkout: self
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                manifests: '$(Pipeline.Workspace)/deployment.yml'
