trigger:
- master

stages:
  - stage: CI
    displayName: 'CI Stage'
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Build
        steps:

        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'clean package'

        - task: DockerInstaller@0
          displayName: 'Install'
          inputs:
            dockerVersion: '17.09.0-ce'

        - task: Docker@2
          displayName: 'Build and Push'
          inputs:
            containerRegistry: 'Docker Registry'
            repository: 'kvncont/hello-world'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.BuildId)'

  - stage: CD_DEV
    displayName: 'CD Dev Stage'
    dependsOn: CI
    jobs:

    - deployment: DeployDev1
      displayName: 'Deploy Dev 1'
      environment: Development.dev1
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                manifests: 'deployment.yml'
                containers: 'kvncont/hello-world:$(Build.BuildId)'

    - deployment: DeployDev2
      displayName: 'Deploy Dev 2'
      environment: Development.dev2
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                manifests: 'deployment.yml'
                containers: 'kvncont/hello-world:$(Build.BuildId)'

  - stage: CD_PRO
    displayName: 'CD Pro Stage'
    dependsOn: CI
    jobs:
            
    - deployment: DeployProEastUS2
      displayName: 'Deploy Pro East US 2'
      environment: Production.proeastus2
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                manifests: 'deployment.yml'
                containers: 'kvncont/hello-world:$(Build.BuildId)'
            
    - deployment: DeployProCentralUS
      displayName: 'Deploy Pro Central US'
      environment: Production.procentralus
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                manifests: 'deployment.yml'
                containers: 'kvncont/hello-world:$(Build.BuildId)'
