trigger:
  - master
  - feature/*

variables:

  - name: k8sNamespaceForPR
    value: $[variables['Build.SourceBranch']]

  - name: resourceName
    value: app

stages:

  - stage: CI
    displayName: CI - Stage
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Build
        steps:

        - task: Maven@3
          displayName: Maven Package
          inputs:
            mavenPomFile: pom.xml
            mavenOptions: -Xmx3072m
            javaHomeOption: JDKVersion
            jdkVersionOption: 1.8
            jdkArchitectureOption: x64
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: clean package

        - task: DockerInstaller@0
          displayName: Install
          inputs:
            dockerVersion: 17.09.0-ce

        - task: Docker@2
          displayName: Build and Push
          inputs:
            containerRegistry: Docker Registry
            repository: kvncont/hello-world
            command: buildAndPush
            Dockerfile: '**/Dockerfile'
            tags: $(Build.BuildId)

  - stage: CD_DEV
    displayName: CD Dev - Stage
    dependsOn: CI
    jobs:

    - deployment: DeployPRDev
      displayName: Deploy Pull Request - Dev
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
      environment: Development.$(k8sNamespaceForPR)
      strategy:
        runOnce:
          deploy:
            steps:

            - reviewApp: app

            - checkout: self

            - task: Kubernetes@1
              displayName: Create a new namespace for the pull request
              inputs:
                command: apply
                useConfigurationFile: true
                inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'

            - task: KubernetesManifest@0
              inputs:
                action: deploy
                manifests: deployment.yml
                containers: kvncont/hello-world:$(Build.BuildId)
                rolloutStatusTimeout: '300'

    - deployment: DeployDev
      displayName: Deploy - Dev
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      environment: Development.app
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: deploy
                manifests: deployment.yml
                containers: kvncont/hello-world:$(Build.BuildId)
                rolloutStatusTimeout: '300'

  - stage: CD_PRO
    displayName: CD Pro - Stage
    dependsOn: CD_DEV
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:

    - deployment: DeployEastUS2Pro
      displayName: Deploy East US 2 - Pro
      environment: Production.eastus2
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: deploy
                manifests: deployment.yml
                containers: kvncont/hello-world:$(Build.BuildId)
                rolloutStatusTimeout: 300
            
    - deployment: DeployCentralUSPro
      displayName: Deploy Central US - Pro
      environment: Production.centralus
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: deploy
                manifests: deployment.yml
                containers: kvncont/hello-world:$(Build.BuildId)
                rolloutStatusTimeout: 300
