trigger:
- master

stages:
  - stage: CI
    displayName: 'CI Stage'
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Build
        steps:

        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'clean package'

        - task: DockerInstaller@0
          displayName: 'Install'
          inputs:
            dockerVersion: '17.09.0-ce'

        - task: Docker@2
          displayName: 'Build and Push'
          inputs:
            containerRegistry: 'Docker Registry'
            repository: 'kvncont/hello-world'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.BuildId)'

  - stage: CD
    displayName: 'CD Stage'
    dependsOn: CI
    jobs:
    - deployment: Deployment      
      environment: Development.default
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                manifests: 'deployment.yml'
