# Si quiere usar este archivo tiene que renombrarlo por skaffold.yaml
apiVersion: skaffold/v2beta13
kind: Config
build:
  # local: {}
  artifacts:
  - image: kvncont/hello-world
    jib:
      args:
        - -DskipTests
deploy:
  kubectl:
    manifests:
    - ./manifests/dev/k8s-*
    defaultNamespace: default